





google_ad_client = "pub-1734388200780924";
google_ad_width = 468;
google_ad_height = 60;
google_ad_format = "468x60_as";


document.write('<SCRI'+'PT type="text/javascript" '); 
document.write('SRC="http://www.anypopup.com/popup.php?ref=arcadearea">');
document.write('</SCR'+'IPT>');


document.write('<SCRI'+'PT type="text/javascript" '); 
document.write('SRC="http://pagead2.googlesyndication.com/pagead/show_ads.js">');
document.write('</SCR'+'IPT>');