<?php include ("header.php"); ?>
<br>
<br>

<table id="whole">
<tr valign="top">
<td align="center"><?php include ("left.php"); ?></td>
<td id="center" align="center">



<table class="dimensions">
	   <tr>
	   	   <td class="catagory">
News
	   	   </td>
	   </tr>
	   <tr>
	   	   <td class="alt1">

	   	   </td>
	   </tr>
</table>



</td>
<td align="center"><?php include ("right.php"); ?></td>
</tr>
</table>
